### ISSUE TITLE
Should provide `swap` (and bug to fix, if you do)

### ISSUE THREAD

**Issue by Quuxplusone** [arturbac/small_vectors#4]
Found by eyeballing the code: The definition of [`uninitialized_uneven_range_swap`](https://github.com/arturbac/small_vectors/blob/master/include/small_vectors/detail/uninitialized_constexpr.h#L308-L320) seems to be dead code. It's used in [`static_vector_storage::swap`](https://github.com/arturbac/small_vectors/blob/master/include/small_vectors/detail/vector_storage.h#L240-L246), but that member function is (1) constrained away in the case that `value_type` is move-only, and (2) still dead; even if `value_type` is copyable, neither `static_vector` or `small_vector` have a `swap` method that would _call_ `static_vector_storage::swap`!

However, suppose you were to add a `swap` method a la `vector::swap`:
```
  void swap(static_vector& b) noexcept { storage_.swap(b.storage_); }
```

Then you would have this bug:

```
cat >test.cpp <<EOF
#include <small_vectors/static_vector.h>
#include <cstdint>
#include <cstdio>

struct S {
  int i_;
  explicit S(int i) : i_(i) { printf("Ctor %d (%p)\n", i_, this); }
  S(S&& rhs) noexcept : i_(rhs.i_) { printf("Move-ctor %d (%p -> %p)\n", i_, &rhs, this); }
  S(const S&) noexcept;
  S& operator=(const S&) noexcept;
  S& operator=(S&&) noexcept;
  ~S() { printf("Dtor %d (%p)\n", i_, this); }
  friend void swap(S& a, S& b) { printf("Swap %d<->%d (%p <-> %p)\n", a.i_, b.i_, &a, &b); std::swap(a.i_, b.i_); }
};

int main() {
  small_vectors::static_vector<S, 10> a;
  small_vectors::static_vector<S, 10> b;
  a.emplace_back(1);
  a.emplace_back(2);
  b.emplace_back(3);
  a.swap(b);
}
EOF
g++ -std=c++23 -I ./include/ test.cpp
./a.out
```
prints:
```
Ctor 1 (0x16b2c341c)
Ctor 2 (0x16b2c3420)
Ctor 3 (0x16b2c33f0)
Swap 3<->1 (0x16b2c33f0 <-> 0x16b2c341c)
Move-ctor 2 (0x16b2c3420 -> 0x16b2c33f4)
Dtor 1 (0x16b2c33f0)
Dtor 2 (0x16b2c33f4)
Dtor 3 (0x16b2c341c)
```

Notice that it move-constructs from 0x16b2c3420 to 0x16b2c33f4, but then forgets to ever destroy the moved-from object that remains at 0x16b2c3420. That's because [`uninitialized_uneven_range_swap`](https://github.com/arturbac/small_vectors/blob/master/include/small_vectors/detail/uninitialized_constexpr.h#L308-L320) should be using `uninitialized_relocate`, not `uninitialized_move`.

Suggested fix: Use `uninitialized_relocate` in `uninitialized_uneven_range_swap` (which, btw, personally I'd drop the `uninitialized_` prefix from the latter because both input ranges are expected to _have_ initialized elements in them already, even if they are different lengths — which the name already reflects in the word `uneven`). Then, add member-function and ADL-hidden-friend `swap` to both `static_vector` and `small_vector`. And unit tests for the latter, especially involving a type T where destroying a moved-from T is observably different from a no-op (e.g. at least keep a count of live objects, and assert that the count is zero at the end of every unit test). Finally, change the constraint on `swap` to permit swapping `small_vector<MoveOnly>` (and add tests).

**Comment by arturbac** [comment]
Thx for info, I'll take a look at that.

**Comment by arturbac** [comment]
IMHO "because both input ranges are expected to have initialized elements in them already,"
if sizes are different the when moving from larger to smaller the surplus elements over smaller size will go to place that could be uninitialized/not constructed before at all.

**Comment by Quuxplusone** [comment]
> when moving from larger to smaller the surplus elements over smaller size will go to place that could be uninitialized

Correct, that part is fine. The problem isn't that we construct _more_ elements than needed (we don't).

The problem is that we destroy _fewer_ elements than we should. Here's the same example from above, visually. Suppose we have a type that holds "A", "B", "C", etc. when full, "X" when moved-from, and nothing-at-all when empty. Swapping these two ranges:

    2: AB
    1: C

should result in [swap A+C, relocate B]

    1: C
    2: AB

but the current code (using only `uninitialized_move`, not `uninitialized_relocate`) results in this instead [swap A+C, move-from B]:

    1: CX
    2: AB

Nobody ever destroys the moved-from object "X"; we just forget that it's there, and any resources it controls will leak. (For example, if it's a MSVC `std::list`, its sentinel node will leak.)

**Comment by Quuxplusone** [comment]
LGTM! 👍

**Comment by arturbac** [comment]
Thank You for reporting this issue.
You were definitely right about that bug.
IMHO reason I didn't find this bug so far is I don't use swap at all in production code, usually moving is enough for me.

**Comment by arturbac** [comment]
FYI:
https://github.com/arturbac/small_vectors/discussions/8

template<typename T>concept simple_reclocatable
